language: cpp

sudo: false

addons:
  apt:
    packages:
      - libconfig++-dev
      - liblog4cpp5-dev

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install libconfig-hr log4cpp; fi

install:
  - curl -L https://github.com/nukedzn/psocksxx/releases/download/v1.0.0/psocksxx-1.0.0.tar.gz | tar -zx -C /tmp
  - cd /tmp/psocksxx-* && ./congifure --prefix=/tmp/root && make && make install

before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then libtoolize; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then glibtoolize; fi
  - aclocal
  - autoheader
  - autoconf
  - automake --add-missing
  - PKG_CONFIG_PATH=/tmp/root ./configure

script:
  - make distcheck

os:
  - linux
  - osx

