language: cpp

sudo: false

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install libconfig; fi

install:
  - curl -L https://github.com/nukedzn/psocksxx/releases/download/v1.1.1/psocksxx-1.1.1.tar.gz | tar -zx -C /tmp
  - cd /tmp/psocksxx-* && ./configure --prefix=/tmp/root && make && make install
  - if [ $TRAVIS_OS_NAME == linux ]; then curl -L http://www.hyperrealm.com/packages/libconfig-1.4.10.tar.gz | tar -zx -C /tmp; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then cd /tmp/libconfig-* && ./configure --prefix=/tmp/root && make && make install; fi
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - PKG_CONFIG_PATH=/tmp/root/lib/pkgconfig cmake -H. -Bbuild -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release

script:
  - cmake --build build

os:
  - linux
  - osx

